### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by CodeArtha** [elementary/calendar#110]
I followed the installation instruction found on the github readme.
I'm on Ubuntu 16.04 running Unity. I could install all dependencies without a single problem. I could configure and build the environment. I got an error when running "sudo make install" and I don't understand what went wrong when reading console output.

`/maya_calendar/build$ sudo make install
[  0%] Built target i18n
[ 24%] Built target libmaya-calendar
[ 84%] Built target maya-calendar
[ 89%] Built target maya-calendar-daemon
[ 94%] Built target caldav
[100%] Built target google
Install the project...
-- Install configuration: ""
-- Installing: /usr/share/locale/id/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ss/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ee/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ca/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ro/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/so/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ks/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/bm/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/sd/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/cv/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/eo/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/st/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ml/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/su/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/gd/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ja/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/it/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ki/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/be/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/av/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/nl/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/as/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/yo/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ka/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/gl/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/fr_CA/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/nr/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ur/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/kj/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/tk/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/zh_CN/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/el/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ht/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/bs/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/eu/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ru/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ba/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ig/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ky/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/rue/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/oc/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/bi/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/pl/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ny/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/et/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/tg/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/kw/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/en_AU/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/os/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/fo/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ts/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/sk/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/hy/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/bg/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/yi/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/he/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/uz/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/lb/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/hr/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/se/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/iu/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/tt/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/om/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ay/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ve/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/li/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/vi/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ae/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ha/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/nb/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ko/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/wo/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ga/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/co/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/za/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/mg/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/te/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ms/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/pi/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/mk/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ff/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/kl/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/oj/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ti/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/hi/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/bh/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ik/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/zh_HK/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/en_CA/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/tr/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/lv/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/am/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/uk/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ln/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/sa/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/tl/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ug/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/lt/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/sm/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/sl/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/mn/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/io/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ce/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/sv/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/sc/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ie/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/fy/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/pt_BR/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/es/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/gn/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/no/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ty/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/kr/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ng/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/la/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ia/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/lo/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/mi/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/aa/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/my/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/tw/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/to/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/lu/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/si/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/fa/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/mr/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/is/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ast/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ar/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/vo/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/sq/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/mo/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/cu/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ho/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/rw/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ii/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/sn/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/hu/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/sma/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/th/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/gv/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/tn/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/nn/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ckb/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/sg/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/br/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/zu/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/hz/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/zh/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/kv/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/cr/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/af/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ch/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ne/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/dv/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/az/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/bo/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/kg/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/pa/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/fr/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/zh_TW/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/kn/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/km/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/gu/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/or/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/fi/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ps/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/cy/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/na/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/sw/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/mt/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/qu/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/bn/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/pt/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ak/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ku/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/rn/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/jv/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/da/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/an/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/dz/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/en_GB/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/wa/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ab/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/sr/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/nd/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/kk/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/xh/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/de/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/lg/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/mh/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/fj/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/cs/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/ta/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/rm/LC_MESSAGES/maya-calendar.mo
-- Installing: /usr/share/locale/nv/LC_MESSAGES/maya-calendar.mo
-- Up-to-date: /usr/share/maya-calendar/style/sidebar.css
-- Up-to-date: /usr/share/maya-calendar/style/default.css
-- Up-to-date: /usr/share/maya-calendar/style/calendar.css
-- Up-to-date: /usr/share/maya-calendar/LocationMarker.svg
-- Up-to-date: /usr/share/icons/hicolor/scalable/actions/calendar-go-today.svg
CMake Error at data/cmake_install.cmake:76 (file):
  file INSTALL cannot find
  "/home/codeartha/Applications/maya_calendar/build/data/org.pantheon.maya.appdata.xml".
Call Stack (most recent call first):
  cmake_install.cmake:38 (include)
  

Makefile:61: recipe for target 'install' failed
make: *** [install] Error 1
`

It just seems that this file is missing: org.pantheon.maya.appdata.xml. Where can I find this file, what have I done wrong for not having this file after cloning this repo?

**Comment by matzipan** [comment]
Looking at [this](https://github.com/elementary/calendar/blob/master/data/CMakeLists.txt#L9) line, can you confirm you have a file build/data/org.pantheon.maya.appdata.xml.in ?

**Comment by CodeArtha** [comment]
Yes I have all three of these files: org.pantheon.maya.appdata.xml.in org.pantheon.maya.desktop.in org.pantheon.maya-original.desktop.in

**Comment by CodeArtha** [comment]
apparently org.pantheon.maya.appdata.xml is not the only one missing, as I tried to create it with an example I found online. And when installing it was org.pantheon.maya.desktop that was now missing. However I coudn't find an example version of the later on internet.

**Comment by tintou** [comment]
you need `intltool` to build this package

**Comment by CodeArtha** [comment]
Thank you a lot, that did the trick. I installed intltool then rebuilded and it installed correctly.
