### ISSUE TITLE
The "Suggest Translation" button is pointing to the wrong link

### ISSUE THREAD

**Issue by GabrielMGitHub** [elementary/calendar#115]
The "Suggest Translation" button is pointing to the wrong link. This error has several applications.
https://translations.launchpad.net/maya

![captura de tela de 2017-05-27 14-19-10](https://cloud.githubusercontent.com/assets/8754997/26523142/7ec0e798-42e7-11e7-9b66-696441bc133f.png)

**Comment by leonardo-lemos** [comment]
Already fixed in trunk.
