### ISSUE TITLE
When adding multi-day event in the future, pop-up calendar suggests today's date as end date

### ISSUE THREAD

**Issue by cameralibre** [elementary/calendar#123]
Apologies for the confusing title, a screenshot works much better :)
I have already selected October 10th as my start date, and thus end dates **before** October 10th are impossible.
![future multi-day event](https://user-images.githubusercontent.com/15368010/27875007-fa650b66-61b1-11e7-8a58-19716679540d.png)
But the calendar pops up showing July 5th (today's date).

As I have already set my event to start on October 10th, the pop-up calendar should display October 10th as the default end date. I can then easily navigate to the correct end date, eg October 11th.

**Comment by Thalexander** [comment]
This is an issue with granite, that has now been resolved.
