### ISSUE TITLE
Editing an event causes a duplicate event to show in the grid momentarily

### ISSUE THREAD

**Issue by dahenson** [elementary/calendar#127]
Steps taken:
1. Create an event and save it
2. Double-click the event in the sidebar to edit it
3. After editing, save the event

Observation:
After clicking "Save Changes," the event gets duplicated in the main grid momentarily, then the grid refreshes and the duplicate entry is removed.

Why is this an issue?
This doesn't seem to be a necessary visual feature of the program, and fixing the issue will help polish the editing workflow.

**Comment by UsefulVid** [comment]
The issue seems to be back.
![vmplayer_IY8Z3JftyW](https://user-images.githubusercontent.com/39967070/90510905-fd875600-e15b-11ea-8171-771ef1acd497.png)


```
libmaya-calendar0/bionic,now 5.0.6+r1806+pkg130~ubuntu5.1.5.1 amd64  [Installiert,automatisch]
maya-calendar/bionic,now 5.0.6+r1806+pkg130~ubuntu5.1.5.1 amd64  [Installiert,automatisch]
maya-calendar-daemon/bionic,now 5.0.6+r1806+pkg130~ubuntu5.1.5.1 amd64  [Installiert,automatisch]
maya-calendar-plugin-caldav/bionic,now 5.0.6+r1806+pkg130~ubuntu5.1.5.1 amd64  [Installiert,automatisch]
maya-calendar-plugin-google/bionic,now 5.0.6+r1806+pkg130~ubuntu5.1.5.1 amd64  [Installiert,automatisch]
```

The calendar in question is a caldav calendar
