### ISSUE TITLE
CALDEV URI with a Port Not Recognized

### ISSUE THREAD

**Issue by ganakee** [elementary/calendar#140]
When setting up or editing a CALDEV calendar, the CALDEV URL field does not handle non-standard ports for the CALDEV server. When the URI is created, the URI assumes default ports (80 or 443) and strips the custom port from the URL. The stripped port does not allow access to the CALDAV resource. Unfortunately, no error displays letting the user know of the issue. The calendar simply does not sync.

I looked at the code (elementary/calendar/plugins/CALDAV/caldevbackend.vala) and see the genesis of the issue. Line 146 (creating the Soup URI) uses defaults and thus the port defaults to standard ports (see Soup URI API docs). This works fine if standard ports are used, but does not work for custom ports.

[Reporter plans to try to work on this issue.]

**Comment by Thalexander** [comment]
Yeah this has been around for a while #37
