### ISSUE TITLE
Map initialised inappropriately when no location

### ISSUE THREAD

**Issue by jeremypw** [elementary/calendar#151]
When the location panel is opened for an event with no location, the map shows (in my case) somewhere in Germany, even though locale and timezone would indicate UK/London.

**Comment by Thalexander** [comment]
I think it attempts to get the location for your IP and seems to show approximately where I live when I open it with no location.

**Comment by jeremypw** [comment]
Doesn't work for me - I am on a home network with a local address (192.168....) there should at least be a fallback if geolocation by IP address fails.
