### ISSUE TITLE
Week number panel not hiding

### ISSUE THREAD

**Issue by Thalexander** [elementary/calendar#169]
When hiding the week numbers the panel does not always hide correctly, and this persists over relaunches of the application.

With week numbers:
![screenshot from 2017-10-01 19 40 15](https://user-images.githubusercontent.com/18336287/31057837-0c7cde90-a6e1-11e7-9cb4-955d6f48bd42.png)

Without:
![screenshot from 2017-10-01 19 40 04](https://user-images.githubusercontent.com/18336287/31057840-14789be8-a6e1-11e7-9055-8d2c787a9fae.png)

**Comment by Thalexander** [comment]
I can't reproduce this on another computer however.

**Comment by danrabbit** [comment]
This is probably due to animations being disabled on that device. Gtk.Revealer will reserve space for itself even while hidden in this case
