### ISSUE TITLE
Adding a Google calendar "destroys" the calendar

### ISSUE THREAD

**Issue by shroudedcode** [elementary/calendar#180]
I just added my Google calendar to Maya. It worked and the events were synced. But after I closed and reopened it, Maya refused to start and exited immediately.

*The calendar's `*.source` file:*
```desktop
[Data Source]
DisplayName=Google Calendar
Enabled=true
Parent=google-stub

[WebDAV Backend]
AvoidIfmatch=false
CalendarAutoSchedule=false
DisplayName=
EmailAddress=
ResourcePath=/calendar/dav/niklas@shroudedcode.com/events
ResourceQuery=
SslTrust=

[Offline]
StaySynchronized=true

[Calendar]
BackendName=caldav
Color=#729FCF
Selected=true

[Authentication]
Host=www.google.com
Method=plain/password
Port=443
ProxyUid=system-proxy
RememberPassword=true
User=niklas@shroudedcode.com
CredentialName=

[Security]
Method=tls
```

The error when starting `maya-calendar`:
```
[INFO 19:43:14.142099] Application.vala:153: Calendar version: 0.4.0.2
[INFO 19:43:14.142137] Application.vala:155: Kernel version: 4.10.0-37-generic
[WARNING 19:43:14.237942] [e-data-server] e_module_load_all_in_directory: Error opening
directory '/usr/lib/evolution-data-server/credential-modules': No such file or directory
[FATAL 19:43:14.258152] maya_util_is_all_day: assertion 'dtend != NULL' failed
[FATAL 19:43:14.258189] [GLib] g_date_time_format: assertion 'datetime != NULL' failed
Segmentation fault (core dumped)
```

A similar/the same issue was already reported [here](https://bugs.launchpad.net/wingpanel-indicator-datetime/+bug/1627283).

---

### Further experimentation

I somehow got Maya to start again and finish synchronizing (the spinner in the top left corner went away). At that point, I was in a month view that didn't contain any events from the Google calendar. After switching to a different month that did contain a Google calendar event, Maya crashed again with exactly the same error.

**Comment by Thalexander** [comment]
Maybe google is using duration rather than dtend (https://tools.ietf.org/html/rfc5545#section-3.6.1) and we are not handling that correctly... We should be able to calculate a dtend from the duration to fix this, although if there are multiple durations that may complicate this.
