### ISSUE TITLE
Plus button in Calendar event creation in the Alarm and Repeat tabs is inconsistent

### ISSUE THREAD

**Issue by D0J0P** [elementary/calendar#207]
Going into the Calendar app and pressing "Create a new event" and then going into the Alarm and Repeat tabs, and hovering your mouse over the plus button gives it a dark gray background that almost hides the button and is probably unintentional. A picture can be seen here: https://imgur.com/3sLsSOU

When you go into other Elementary apps like System Settings, and go into a setting where you can add something(like Bluetooth, Printer or Keyboard), you don't see that effect on the plus button when you hover over it.

**Comment by dahenson** [comment]
Can you still reproduce this issue? I am unable to reproduce with the current build of Calendar.
