### ISSUE TITLE
Select event's Calendar using keyboard?

### ISSUE THREAD

**Issue by peteruithoven** [elementary/calendar#214]
When entering a new event I would love to be able to select the target Calendar using just my keyboard. Especially since I just typed the title and I'll might need to type again to enter the time for example. 

On the web the convention for dropdown menu's seems to be that typing the desired value results in that value being automatically selected. It's also possible to traverse all the values using the arrow keys. 

Relevant Widget: [CalendarButton](https://github.com/elementary/calendar/blob/master/src/Widgets/CalendarButton.vala)

**Comment by danrabbit** [comment]
From my testing:
* The calendarbutton widget can be focused from the event creation dialog by tabbing from the title entry
* It can be activated with either the enter or space keys
* the list of calendars can be navigated with the keyboard and activated with either the enter or space keys

It seems that all that's left here is being able to filter the listbox by typing
