### ISSUE TITLE
Green title bar

### ISSUE THREAD

**Issue by Vento09** [elementary/calendar#223]
The calendar could have its title bar colored green as its icon. This would give a very interesting visual cohesion to the system.

![calendario final](https://user-images.githubusercontent.com/30022019/36254809-9e23f550-1233-11e8-833a-0e26042e7534.png)

The green I used in the image  is from the elemenatary's color palette.

**Comment by cassidyjames** [comment]
I think this spurs a wider question of: should default apps have brand coloring? I've also poked at Music, trying out the orange theme color. I personally like exploring the idea, but I think we'd want to decide if we want to do it across the board, then either do it or don't. :) 

My main concern is if everything is bright and colorful, it could make the OS feel a lot more playful instead of reserved and professional. I'm not sure if that's a realistic concern or not, though, and I'm interested in exploring this more.

@elementary/ux?

**Comment by Vento09** [comment]
Now I'll show you my advantages and disvantages of the color title bar.
### Vantages
1. **It will make the calendar more "beatiful"**: when I say beatiful, I want to say it will have an ID, that means the calendar will be single and simple. The color in the app will provide a charm and distinguishing feature of the applications.
2. **The elementary OS is going to "move away" from MacOS**: Most Mac apps have its title bar gray like the elementary OS but why is it advantageous? Because in the majority reviews of the elementary OS in Youtube say that the elementary is a "Linux that copies Mac". With title bar colored the elementary will take a step against it. I suggest yellow for mail, orange for music, green for calendar, purple for app center.
3. **Improve the velocity of Multitasking view**:  See the Image below:

![multitasking view](https://user-images.githubusercontent.com/30022019/36305772-23ba6406-12fc-11e8-95e9-32da123bf102.png)
   If you see quickly, you won't see the calendar upper right corner. Probably you saw first the  Chrome icon which is colorful and then the Eddy red color. The calendar is almost "invisible" in the image. With the green title bar,  it's much easier to open the calendar than before which would improve UX.

### Disadvantages
1. **It leaves the system less professional**: I understand, but there apps with title are colorful that many professionals use. Example Microsoft Office. The blue on top of the Word doesn't disturb the people to write.
2. **It will spend time programming**: I want to see big changes in Juno. A color in the bar is almost nothing. But I think this concern in the UI / UX that elementary has is that it differs from Linux Mint. Linux Mint has far more facilities than the elementary, but the elementary care it has makes it much more enjoyable to use.

That is it! Thank for reading and sorry for my english :).

**Comment by yavinfour** [comment]
@Vento09 interesting suggestion. Though I don't believe it should be implemented. The user interface should melt away and only reveal what the user needs to see. The bright green bar, or any other color than the user interface standard, calls too much attention to a user interface element that is already filled with a lot of functionality. I think the title bar could actually be less complex.

I'd like to see the arrows gone and perhaps a drop down that shows the months and a dropdown that shows years. If you'd like to keep the left/right arrows, perhaps remove the outline/border of the button. I'd also like to see the icon that is supposed to indicate "Go to today's date" replaced with a button that simply says "Today" designed similarly to the month and year buttons. The icon is a little cryptic and I shouldn't have to guess at what it does. I know there is a hint, but the hint should not be necessary.

Also, the previous month and next month calendar days should be a lot lighter, in my opinion.

**Comment by miko007** [comment]
@Vento09 
> Because in the majority reviews of the elementary OS in Youtube say that the elementary is a "Linux that copies Mac". With title bar colored the elementary will take a step against it. 

This is actually the reason a lot of people i know personally are using elementary, because it copies macOS. I do not think the project would benefit from "stepping against" that.

**Comment by harveycabaguio** [comment]
An issue here is that the green makes some of the icons harder to distinguish since its green on green

**Comment by LewisOdam** [comment]
I don't think a green title bar would look very nice at all. One of the main characteristics about eOS is its unified UI across its APPS. This it what gives it a very polished and professional feel when compared to any/many other distro's and sacrificing this would have a negative impact on the way it feels to use.
What is being suggested here reminds me of the flat bright colours of Win10, and if there is one thing about Win10 that most might agree is not to pleasant it is the childish, toy box appearance on the UI.
"Looking Like" Mac OS is certainly not a bad thing, if there is one thing Apple do actually do well it is make attractive UI's and devices, so taking the best from that is where eOS seems to be getting it right. 
Grey scale and dark themes work well together in eOS but I dont think coloured title bars is the way forward here. IMO.

**Comment by eljefuri** [comment]
Personally I don't give a damn about how professional _(whatever that means)_ Elementary and its default apps look. I just care that they are clear, beautiful, and undistracting. That green looks pretty terrible to me.

**Comment by eljefuri** [comment]
@LewisOdam I don't think that Elementary should copy Apple's application or general OS aesthetics; Apple definitely went overboard and shot their own guidelines out the window starting with Mac OS X 10.7. See the Address Book evolution from [10.6](https://posteo.de/system/help_images/268/original/Calendar%20Setup%20-%20Mac%2003.png?1404318769) to [10.7](https://i2.wp.com/www.thegraphicmac.com/wp-content/uploads/mac_lion-screenshot.jpg?resize=550%2C343) for example. Functional? _Yes._ Useful? _Perhaps._ Beautiful? _Highly arguable._

On the other hand, I do think that Elementary should copy heavily and unashamedly from Apple's UX guidelines, which represents 40+ years of best-in-class testing and research. That is not to say that they got everything right, but they definitely put more time and money into this than anyone else in the field.

**Comment by fabiozaramella** [comment]
Marking as Design Conflict and closing since the idea of brand colors for default apps has been abandoned (also, now default apps use their own accent color).
