### ISSUE TITLE
Support CalDAV tasks

### ISSUE THREAD

**Issue by alexgleason** [elementary/calendar#232]
Adding support for tasks would be a nice addition. It's part of the CalDAV prototcol.

**Comment by danrabbit** [comment]
Going to close this as "Out of Scope" since a separate app focused on tasks would be a better experience

**Comment by elbakkayg** [comment]
google tasks synchronizes with google calendar, it's one of the best user experience in time management to have everything on your calendar in the morning (tasks, events, reminders) and google tasks with google calendar remain two separate applications.

The user experience is not a monolithic experience ..!

![Screenshot from 2020-02-24 12 24 27](https://user-images.githubusercontent.com/60742919/75150885-a7ce7580-5705-11ea-8f0d-e2b2692ead66.png)

**Comment by matfantinel** [comment]
I'd add that the main point of having tasks displayed on the Calendar is not really managing them, but the ability to have a quick glance at the day.

I often want to have a quick glance at what's going on in my day, specially in the morning. But the information is split between the events (meetings, appointments, etc) and the tasks (do laundry, work on X, etc).

Apps like Google Calendar are able to display the CalDav tasks (with a date) on them amongside the events, but open them on the dedicated Tasks app if you interact with them. This makes for a very well integrated experience (which coming from Google is kinda rare 😝)

**Comment by giuliohome** [comment]
See my approach to solve this issue that I have described [here](https://gitlab.gnome.org/GNOME/gnome-calendar/-/issues/923)
