### ISSUE TITLE
Lock screen does not respect time settings

### ISSUE THREAD

**Issue by inad9300** [elementary/calendar#241]
I didn't know in which repository to open this issue (I often have this problem...) Please, redirect me appropriately.

In the System Settings application, I have set the "Time format" setting to "24h". However, the lock screen shows the time with the AM/PM format.

**Comment by tintou** [comment]
Thanks for your report!
The component you're searching is https://github.com/elementary/greeter
It is reported at https://github.com/elementary/greeter/issues/52
