### ISSUE TITLE
Connect gmail account via oauth2 api [$10]

### ISSUE THREAD

**Issue by ryonakano** [elementary/calendar#244]
It seems that Calendar does not support OAuth 2.0. At present, we have to allow "less secure apps" to connect Google Calendar.

**Comment by MacOSO** [comment]
To enter, you can use the [Google application passwords](https://myaccount.google.com/apppasswords)

**Comment by danrabbit** [comment]
I'm going to close this as "Out of Scope" because the plan is to handle Google OAuth signin in System Settings → Online Accounts instead of implementing it per-app

**Comment by marcelogdeandrade** [comment]
I've encountered this issue, my Google account had "Less secure app access" disabled, to fix it I had to enable this option.

**Comment by joedborg** [comment]
> I'm going to close this as "Out of Scope" because the plan is to handle Google OAuth signin in System Settings → Online Accounts instead of implementing it per-app

Hi @danrabbit,

Is there somewhere we can follow this progress?  It seems to be working fine for Mail but not Calendar (on 5.1).

Thanks!
