### ISSUE TITLE
Full translation French, Dutch and German

### ISSUE THREAD

**Issue by Ordissimo** [elementary/calendar#250]
I add the complete German translation.
We use professional translators.
If you do not update the project, we can not use Weblate.
Here is the commit for the complete translation of French, Dutch and German:[German](https://github.com/Ordissimo/calendar/commit/f5f55bd3a7229d5d5f1d41d58acba23edaf55be6) and [French and Dutch](https://github.com/Ordissimo/calendar/commit/6046a2542a2c4d9756cdb43cb22c672111790ab9)

**Comment by tintou** [comment]
We just updated our build system to be able to update the translation template, you should now be able to use weblate to translate it completely.
