### ISSUE TITLE
repeatedly requests location access, can never successfully acquire it

### ISSUE THREAD

**Issue by decathorpe** [elementary/calendar#282]
After clicking the button to add a new event, I get the "Location request" notification every time, but it isn't actionable in any way (clicking it does nothing). The following message is printed to the log:

```
** (io.elementary.calendar:2620): WARNING **: 13:34:53.541: LocationPanel.vala:245: Failed to connect to GeoClue2 service: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Agent rejected 'io.elementary.calendar' for user '1001'. Please ensure that 'io.elementary.calendar' has installed a valid io.elementary.calendar.desktop file.
```

It also looks like the pantheon geoclue2 agent is just exiting 10 seconds after starting it, so that might be related: https://github.com/elementary/pantheon-agent-geoclue2/issues/26

**Comment by J0Ar** [comment]
@decathorpe Does this bug still exist? I only ask, because for me now it works as expected.

**Comment by decathorpe** [comment]
No, I can't reproduce it. Thanks for the follow-up!
