### ISSUE TITLE
Event Dialog is not modal

### ISSUE THREAD

**Issue by jeremypw** [elementary/calendar#370]
You can still interact with the calendar main window while the creating an event, including altering the active calendars. This does not seem desirable.

**Comment by mcclurgm** [comment]
I agree, somehow or another, this behavior should change. The interaction could lead to data inconsistencies (haven't checked but seems plausible), but even outside of that the focus behavior causes some usability issues. If I alt-tab away from Calendar and back, it'll focus on the main window and I have to click somewhere in the dialog to get it back in focus.

IMO there are 2 options here. 
1. We could make the event creation/modification completely modal, as many apps seem to do (GNOME, Evolution, all Apple calendars, …). This would make it like a typical popup and it would steal focus.
2. We could commit to it losing focus and make it into a first-class window. This would let people open up multiple events at once and also move around the calendar to check things, which could be very nice. (My non-Linux calendar app of choice, Fantasical, does a great job of this and it's useful. Not often, but when it is it's a huge help) I worry that this would be much more complex though, depending on the types of things that people can mess up in the main window.

Thoughts?

**Comment by jeremypw** [comment]
I would do the easy fix first (make the dialog modal) and then look into allowing the safe editing of multiple events simultaneously at leisure (as a separate wishlist issue).

**Comment by mcclurgm** [comment]
Makes sense, good call. I'll see what I can do.
