### ISSUE TITLE
recent hi translations break builds

### ISSUE THREAD

**Issue by decathorpe** [elementary/calendar#390]
../po/hi.po:215: 'msgid' and 'msgstr' entries do not both begin with '\n'
    ../po/hi.po:221: 'msgid' and 'msgstr' entries do not both begin with '\n'
    ../po/hi.po:247: 'msgid' and 'msgstr' entries do not both begin with '\n'
    ../po/hi.po:261: 'msgid' and 'msgstr' entries do not both begin with '\n'
    ../po/hi.po:267: 'msgid' and 'msgstr' entries do not both begin with '\n'
    ../po/hi.po:363: 'msgid' and 'msgstr' entries do not both begin with '\n'
    ../po/hi.po:369: 'msgid' and 'msgstr' entries do not both begin with '\n'
    ../po/hi.po:406: 'msgid' and 'msgstr[0]' entries do not both begin with '\n'
    msgfmt: found 8 fatal errors

**Comment by codygarver** [comment]
Fixed in master
