### ISSUE TITLE
Build fails: error: use of undeclared identifier '_NL_TIME_FIRST_WEEKDAY'

### ISSUE THREAD

**Issue by 0mp** [elementary/calendar#392]
I get the following error when building Calendar on FreeBSD (I am trying to add Calendar to the ports collection):

> ```
> [16/66] cc -Icore/0d45f5f@@elementary-calendar@sha -Icore -I../core -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include -I/usr/local/include/gee-0.8 -I/usr/local/include/granite -I/usr/local/include/gio-unix-2.0/ -I/usr/local/include/gtk-3.0 -I/usr/local/include/pango-1.0 -I/usr/local/include/fribidi -I/usr/local/include/cairo -I/usr/local/include/pixman-1 -I/usr/local/include/freetype2 -I/usr/local/include/libdrm -I/usr/local/include/libpng16 -I/usr/local/include/harfbuzz -I/usr/local/include/gdk-pixbuf-2.0 -I/usr/local/include/atk-1.0 -I/usr/local/include/at-spi2-atk/2.0 -I/usr/local/include/at-spi-2.0 -I/usr/local/include/dbus-1.0 -I/usr/local/lib/dbus-1.0/include -I/usr/local/include/evolution-data-server -I/usr/local/include/libsecret-1 -I/usr/local/include/libxml2 -I/usr/local/include/libsoup-2.4 -I/usr/local/include/nss -I/usr/local/include/nss/nss -I/usr/local/include/nspr -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -w -O3 '-DGETTEXT_PACKAGE="io.elementary.calendar"' -O2 -fstack-protector -fno-strict-aliasing -fPIC -pthread -D_THREAD_SAFE  -MD -MQ 'core/0d45f5f@@elementary-calendar@sha/meson-generated_Model_CalendarModel.c.o' -MF 'core/0d45f5f@@elementary-calendar@sha/meson-generated_Model_CalendarModel.c.o.d' -o 'core/0d45f5f@@elementary-calendar@sha/meson-generated_Model_CalendarModel.c.o' -c 'core/0d45f5f@@elementary-calendar@sha/Model/CalendarModel.c'
> FAILED: core/0d45f5f@@elementary-calendar@sha/meson-generated_Model_CalendarModel.c.o
> cc -Icore/0d45f5f@@elementary-calendar@sha -Icore -I../core -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include -I/usr/local/include/gee-0.8 -I/usr/local/include/granite -I/usr/local/include/gio-unix-2.0/ -I/usr/local/include/gtk-3.0 -I/usr/local/include/pango-1.0 -I/usr/local/include/fribidi -I/usr/local/include/cairo -I/usr/local/include/pixman-1 -I/usr/local/include/freetype2 -I/usr/local/include/libdrm -I/usr/local/include/libpng16 -I/usr/local/include/harfbuzz -I/usr/local/include/gdk-pixbuf-2.0 -I/usr/local/include/atk-1.0 -I/usr/local/include/at-spi2-atk/2.0 -I/usr/local/include/at-spi-2.0 -I/usr/local/include/dbus-1.0 -I/usr/local/lib/dbus-1.0/include -I/usr/local/include/evolution-data-server -I/usr/local/include/libsecret-1 -I/usr/local/include/libxml2 -I/usr/local/include/libsoup-2.4 -I/usr/local/include/nss -I/usr/local/include/nss/nss -I/usr/local/include/nspr -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -w -O3 '-DGETTEXT_PACKAGE="io.elementary.calendar"' -O2 -fstack-protector -fno-strict-aliasing -fPIC -pthread -D_THREAD_SAFE  -MD -MQ 'core/0d45f5f@@elementary-calendar@sha/meson-generated_Model_CalendarModel.c.o' -MF 'core/0d45f5f@@elementary-calendar@sha/meson-generated_Model_CalendarModel.c.o.d' -o 'core/0d45f5f@@elementary-calendar@sha/meson-generated_Model_CalendarModel.c.o' -c 'core/0d45f5f@@elementary-calendar@sha/Model/CalendarModel.c'
> ../core/Model/CalendarModel.vala:71:24: error: use of undeclared identifier '_NL_TIME_FIRST_WEEKDAY'
>         _tmp0_ = nl_langinfo (_NL_TIME_FIRST_WEEKDAY);
> ```

Here are some related commits/discussions:
- https://github.com/GNOME/vala/commit/ea38039a33ca66f51f47315f4da2c330e4a8fd19
- https://github.com/elementary/calendar/pull/234

Here's the output of the configuration phase:
```
===>  Configuring for calendar-5.0
The Meson build system
Version: 0.49.2
Source dir: /wrkdirs/usr/ports/deskutils/elementary-calendar/work/calendar-5.0
Build dir: /wrkdirs/usr/ports/deskutils/elementary-calendar/work/calendar-5.0/_build
Build type: native build
Project name: io.elementary.calendar
Project version: 5.0
Appending CFLAGS from environment: '-O2 -pipe  -fstack-protector -fno-strict-aliasing '
Appending LDFLAGS from environment: ' -fstack-protector '
Native C compiler: cc (clang 6.0.0 "FreeBSD clang version 6.0.0 (tags/RELEASE_600/final 326565) (based on LLVM 6.0.0)")
Appending LDFLAGS from environment: ' -fstack-protector '
Native Vala compiler: valac (valac 0.44.3)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/local/bin/pkgconf (1.6.0)
Dependency glib-2.0 found: YES 2.56.3
Dependency gee-0.8 found: YES 0.20.1
Dependency granite found: YES 5.2.3
Dependency gtk+-3.0 found: YES 3.24.7
Dependency libecal-1.2 found: YES 3.28.5
Dependency libedataserver-1.2 found: YES 3.28.5
Dependency libedataserverui-1.2 found: YES 3.28.5
Dependency libical found: YES 3.0.4
Dependency libsoup-2.4 found: YES 2.62.3
Dependency gmodule-2.0 found: YES 2.56.3
Dependency champlain-0.12 found: YES 0.12.16
Dependency champlain-gtk-0.12 found: YES 0.12.16
Dependency clutter-1.0 found: YES 1.26.2
Dependency clutter-gtk-1.0 found: YES 1.8.4
Dependency folks found: YES 0.11.4
Dependency geocode-glib-1.0 found: YES 3.26.0
Dependency libgeoclue-2.0 found: YES 2.4.7
Library m found: YES
Configuring io.elementary.calendar-daemon.desktop using configuration
Configuring config.vala using configuration
Program meson/post_install.py found: YES (/usr/bin/env python3 /wrkdirs/usr/ports/deskutils/elementary-calendar/work/calendar-5.0/meson/post_install.py)
Build targets in project: 15
Found ninja-1.8.2 at /usr/local/bin/ninja
```

Let me know if there if I can provide any further help with debugging this issue.

**Comment by tintou** [comment]
We rely on GLibc here to provide `_NL_TIME_FIRST_WEEKDAY` in `langinfo.h` so there is nothing that we can do on our side, if you have a patch to make this work on BSD-like systems, feel free to open a Pull Request
