### ISSUE TITLE
More text is hidden when day is selected

### ISSUE THREAD

**Issue by peteruithoven** [elementary/calendar#399]
I don't understand why the "... more..." text is hidden when a day is selected?
![Screen record from 2019-05-23 18 21 00](https://user-images.githubusercontent.com/523210/58269340-9f689900-7d87-11e9-8433-9edabad62961.gif)

**Comment by dahenson** [comment]
That does seem a bit strange. When you select the day, the events should all show on the Agenda sidebar, but that text shouldn't go away.
