### ISSUE TITLE
Support for SSO with Google Accounts

### ISSUE THREAD

**Issue by joedborg** [elementary/calendar#410]
Currently, only Google credentials are supported.  Some enterprises authenticate via their own SSO.  An example of this working is in Gnome Online Accounts.

**Comment by peteruithoven** [comment]
I don't know what SSO is but should this be opened in our online accounts section?
https://github.com/elementary/switchboard-plug-onlineaccounts/issues

I know currently you still authenticate etc in calendar itself but more is going to move to the online accounts settings.

**Comment by danrabbit** [comment]
Closing as a duplicate of https://github.com/elementary/calendar/issues/244
