### ISSUE TITLE
Caldav usability

### ISSUE THREAD

**Issue by linuxr01** [elementary/calendar#412]
In the calendar app i have to add the full caldav path. Make it like MacOS,Android and iOS.
Only enter the caldav server. HTTPS should be default.

Example:
![grafik](https://user-images.githubusercontent.com/49744994/61875905-ed1a9280-aeeb-11e9-8497-0140bb085f9d.png)
![grafik](https://user-images.githubusercontent.com/49744994/61875924-f86dbe00-aeeb-11e9-8145-34f9eab8a41e.png)

**Comment by peteruithoven** [comment]
We're going to be moving this logic to the online account settings. So I'm closing this issue as out of scope for the calendar.
