### ISSUE TITLE
The google integration doesn't work at all.

### ISSUE THREAD

**Issue by wedsonlopes** [elementary/calendar#418]
The google integration doesn't work.

**Comment by ezeveliz** [comment]
Look for "Evolution" in the AppCenter, install it, now add your google account to it, now your calendar will appear in the Calendar app, it's not ideal but it works.
PS: you can uninstall Evolution after syncing your account.

**Comment by CameronNemo** [comment]
My issue was that I was not using the application passwords functionality for my google account.
