### ISSUE TITLE
Bug in creating new calendar

### ISSUE THREAD

**Issue by liorlobel** [elementary/calendar#422]
Hi, 
I was trying to sync a Nextcloud webdav calendar so I created a new calendar, but it kept failing, no error given. I dropped to the terminal and got the following error - 
``` ** (io.elementary.calendar:6580): CRITICAL **: 15:06:35.595: maya_cal_dav_backend_real_add_new_calendar: assertion 'color != NULL' failed ```

So I tried again, this time changing the default color and it worked! . It seems that the default color selection is probably no selection and that fails the addition of the calendar without giving an error. 

Thanks

**Comment by ryonakano** [comment]
This issue was fixed in #387, but a new version of Calendar that includes this fix has not been released yet.
