### ISSUE TITLE
Calendar does not compile

### ISSUE THREAD

**Issue by Enerccio** [elementary/calendar#433]
Can someone tell me why someone committed into repository a code that won't actually compile?

There is no return here:

https://github.com/elementary/calendar/blame/ec172c923cefed0a31845651b3ad3580b045632b/vapi/libical.vapi#L1973

**Comment by Enerccio** [comment]
Was @tintou drunk? :D Another method fails as well

**Comment by tintou** [comment]
It compiles with the very latest Vala (which was a regression that is now fixed in https://gitlab.gnome.org/GNOME/vala/commit/bbaae36410699887cf6b9cacee0181a78d0638f0 )

**Comment by Enerccio** [comment]
this project should have travis though because any compilation would have caught that bug

**Comment by tintou** [comment]
It has travis already and this compiled with some Vala versions

**Comment by tintou** [comment]
Fixed
