### ISSUE TITLE
Does not connect to the Google Calendar

### ISSUE THREAD

**Issue by beretar-tg** [elementary/calendar#468]
When I try to connect to the Google Calendar, I get a 401 error.

login and password are 100% correct

![изображение](https://user-images.githubusercontent.com/57799024/69799224-ef676300-11e3-11ea-8a84-94abeaa4a0cc.png)

**Comment by coco74x** [comment]
I have the same issue. I cannot log in to my google account :(

**Comment by tintou** [comment]
It is probably because of 2 Factor Authentication: https://elementaryos.stackexchange.com/questions/15245/unable-to-validate-gmail-mail-account-username-or-password-error

**Comment by coco74x** [comment]
It is working with password app.

**Comment by otavioschwanck** [comment]
Same issue here

**Comment by tintou** [comment]
The answer is on the Google side that doesn't allow you to use your real password to connect, see https://elementaryos.stackexchange.com/questions/15245/unable-to-validate-gmail-mail-account-username-or-password-error
