### ISSUE TITLE
Reminders in Calendar on Elementary 5.1 do not work

### ISSUE THREAD

**Issue by ernmander** [elementary/calendar#474]
Reminders in the calendar app in Elementary 5.1 do not work. No notification pop us or anything. Leads to missing appointments, meaning Elementary OS 5.1 can't be considered for my daily driver OS.

**Comment by Pliavi** [comment]
![Captura de tela de 2019-12-09 12-28-33](https://user-images.githubusercontent.com/5985423/70448669-74256d00-1a7f-11ea-8fd0-fd138a275ca6.png)


Same here, it looks like it's not being saved, as you set the reminders, save, and goes back to the reminders area, all of them have been disappeared.

**Comment by wout** [comment]
I would like to add here that reminders can be added through any other calendar app, and then they stick. Also after saving the event in eOS calendar with a reminder created in another calendar app.

I am using GNOME calendar now for those features that do not work in eOS calendar. Like setting reminders and weekly recurring events.

Configuring another calendar app as default in settings does not work either. Not really an elementary OS workflow though. :nerd_face:

**Comment by 4jNsY6fCVqZv** [comment]
Is it already possible to make a new release to close the issue?

**Comment by nick87720z** [comment]
When adding reminder in maya-calendar, evolution show it as (vaguely remembering) for event if unknown type, though maya can't display them. Those, added with evolution itself, are visible in maya (though no way to edit it without eveolution too).
