### ISSUE TITLE
Duplicate calendar item using the context menu

### ISSUE THREAD

**Issue by wolframroesler** [elementary/calendar#475]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**

It's not possible to create an exact duplicate of an existing calendar entry. For example, I manage an event calendar for a local user group; calendar items repeat every four weeks and are all similar (same headline, same URL, etc.), but Calendar doesn't support me in any way in creating a new calendar item that's identical to an existing one.

**Describe the solution you'd like**

Add "Duplicate" to the context menu when right-clicking a calendar item (which currently contains "Remove" and "Edit"). Creates and saves a new calendar item identical to the one that was right-clicked (no intermediate dialog). The user can then double-click one of the two items and edit it.

**Existing work**

The macOS calendar application has been doing it this way for years.

**Describe alternatives you've considered**

Since Elementary Calendar doesn't even seem to support copy/paste of complete calendar items, the only alternative I can think of is to use a different calendar program.

**Additional context**

Screenshot of the context menu in macOS.

![Bildschirmfoto 2019-12-15 um 12 10 46](https://user-images.githubusercontent.com/25565229/70862095-fdcdb280-1f37-11ea-8388-40e63b980890.png)

**Comment by wolframroesler** [comment]
Maybe I should have waited until someone put a bounty on it :) but I needed it right away, so here's my implementation.

**Comment by fabiozaramella** [comment]
This has been fixed with #520
