### ISSUE TITLE
Icon not showing due to translation

### ISSUE THREAD

**Issue by cassidyjames** [elementary/calendar#477]
How can we prevent this from happening? :grimacing: Can we add a translator comment in the .desktop file at least?

https://elementaryos.stackexchange.com/questions/21665/why-does-the-calendar-icon-not-show-up

**Comment by cassidyjames** [comment]
Oops, wrong translation… trying to find which one is broken

**Comment by danrabbit** [comment]
I think we found that translator comments don't show for .desktop files. I believe this is fixed in a newer version of gettext upstream, but for now all we can really do is double check the generated files before release.

Looks like `uk` is the culprit

**Comment by tintou** [comment]
You can put a comment for the source string in weblate but until Gettext supports the [version 1.3 of the Freedesktop Desktop documentation](https://specifications.freedesktop.org/desktop-entry-spec/latest/ape.html#idm45854576332816)

**Comment by tintou** [comment]
Which is done in this commit https://git.savannah.gnu.org/gitweb/?p=gettext.git;a=commit;h=1c9b7215050412f75b3cb6348aaec13206c7ad20

**Comment by danrabbit** [comment]
Fixed in weblate, so closing this issue. There was already a comment in Weblate even :upside_down_face:
