### ISSUE TITLE
Can't find ICS import dialog

### ISSUE THREAD

**Issue by CodingSpiderFox** [elementary/calendar#479]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Describe the bug
Cannot find the import ICS functionality.

### To Reproduce
Open elementary calendar, download an ICS file.
I don't see where I can import it.

### Expected behaviour
I'd like to have a menu bar with all the common calendar functions.

### Screenshots or screen recordings
![image](https://user-images.githubusercontent.com/25173078/71507628-0ea5ee80-287d-11ea-859b-19f2617c2e8d.png)

## Platform Information
ElementaryOS 5.1

Please check what applies:
-->
- [ ] I'm using the latest version from git that I've manually compiled
- [X] I'm using the latest released stable version

**Comment by mcclurgm** [comment]
I agree, this makes it hard to know that this functionality exists. This is more of a feature request than a bug though. 

To import an ICS file you have to open the file from Files, and then it'll open in Calendar and import. This makes sense in a way, but it's near impossible to know it's there. It would be very helpful if we could include some way of opening the pane from the Calendar UI. I think it would make sense in the calendar menu, next to the "Add Calendar..." button. Something like this, maybe:
![Screenshot from 2020-05-04 11 36 20](https://user-images.githubusercontent.com/29022469/80995530-9b4c5480-8dfb-11ea-8234-eb9663174467.png)
