### ISSUE TITLE
Repeat option does not work for "monthly"

### ISSUE THREAD

**Issue by wout** [elementary/calendar#487]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Describe the bug
Repeating an event daily, weekly or annually works, but not for monthly.

### To Reproduce
1. Create new event
2. Add title
3. Go to the Repeat tab
4. Repeat monthly

### Expected behavior
Should repeat events monthly.

## Platform Information
![image](https://user-images.githubusercontent.com/107324/73205257-927f1f00-4138-11ea-9d41-61f24cbc9746.png)

Please check what applies:
- [ ] I'm using the latest version from git that I've manually compiled
- [X] I'm using the latest released stable version

## Additional context
Using Google Calendar.

Currently, I use GNOME Calendar to create Monthly recurring events.

**Comment by mkykadir** [comment]
There are two options for monthly repeating,

- [ ] The same day everyday month
- [ x ] Every nth <DayName>

Second option worked for me but first option didn't work, I used a local calendar.
