### ISSUE TITLE
Cache calendars

### ISSUE THREAD

**Issue by knyzorg** [elementary/calendar#503]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**

My college's email server is weirdly configured and makes retrieving my calendar very slow. This is fine on most operating system as the pattern for syncing calendars seems to be:
 - Download ical file
 - Periodically update the ical file
 - Update calendar based on push events from the server (is that I thing?)

It half works in elementary OS as the top-level dropdown seems to follow this pattern:
![this one](https://user-images.githubusercontent.com/10255546/78612735-11c75800-7838-11ea-8688-9a824d4d2518.png)

However, it does not behave that way in the calendar application, where it seems to pull everything on application start, instead of retrieving it from elsewhere first: 
![image](https://user-images.githubusercontent.com/10255546/78612791-30c5ea00-7838-11ea-93dd-00ebc89e25fa.png)

**Describe the solution you'd like**

I think it would be a good idea to keep previously downloaded calendars and load them into the view before attempting to retrieving an update one.

**Comment by knyzorg** [comment]
Getting a view like this should be impossible:
![image](https://user-images.githubusercontent.com/10255546/78612913-784c7600-7838-11ea-9d55-d30c9bfe1820.png)

Maxwell's birthday is visible in one calendar, but absent from the application because its trying to reload it my calendar (while I am offline).

**Comment by marbetschar** [comment]
Related to #492

**Comment by fabiozaramella** [comment]
Closing because it seems that calendars are already cached both when imported from .ics files and when added from caldav or google (if "keep local copy" was selected). The matter is about showing them immediately (see hint in #492), keep Calendar up to date (disccusion in #414) and sync Calendar once connected to the internet (also #492).
