### ISSUE TITLE
Editing "Monthly" repeating events shows wrong "Every:" option

### ISSUE THREAD

**Issue by mkykadir** [elementary/calendar#508]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
Editing a monthly repeating event shows wrong information in "Repeat" tab. Text is always "Every fifth Saturday" for the second option.

### To Reproduce
1. Create event
2. Repeat 'Monthly'
3. Select an option
4. Edit event
5. Go to 'Repeat' tab

### Expected behavior

Second option should display correct information according to the event's date.

### Screenshots or screen recordings

![problem screenshot](https://user-images.githubusercontent.com/3192210/79055277-7594bb00-7c54-11ea-82e3-2dff7d9b26e7.png)

## Platform Information
![platform information](https://user-images.githubusercontent.com/3192210/79055266-5f86fa80-7c54-11ea-88fb-a7949a8ee80f.png)

- [x] I'm using the latest version from git that I've manually compiled
- [ ] I'm using the latest released stable version

**Comment by mcclurgm** [comment]
I'm seeing the same data when I create the event and open the editor. What do you see when you follow those steps?

Here are screenshots of what I see when I create an event:
![create](https://user-images.githubusercontent.com/29022469/79072305-933a4280-7c9d-11ea-842e-35928be89f48.png)
and when I go back to edit it:
![edit](https://user-images.githubusercontent.com/29022469/79072307-9c2b1400-7c9d-11ea-8bf5-70c776c4a0db.png)
I don't see any difference in the data it presents. (I didn't flip the switch back on like #505, in case that does anything)

**Comment by mkykadir** [comment]
I think, I checked this issue with pull request #507 that fixes #487 . I will investigate the pull request and update it accordingly. I am going to update this Issue report with second option behavior, it always shows wrong text.
