### ISSUE TITLE
Can I sync Trello calendar with Elementary OS Calendar?

### ISSUE THREAD

**Issue by zhandosweb** [elementary/calendar#510]
Hello!

Please, tell me. Can I sync the Elementary OS calendar with Trello Calendar? For example, Microsoft Outlook support this feature, check to please this article: https://help.trello.com/article/1064-using-trello-with-microsoft-outlook

**Comment by mcclurgm** [comment]
In the gear menu, there's a an option to add a new calendar. When you're there, you can choose type CalDAV. I believe you can just paste the URL that Trello gives you into that.

In the future, please ask for help at the [elementary Stack Exchange site](https://elementaryos.stackexchange.com/questions/tagged/calendar) unless it's a bug. This site is meant only to track problems with the app, and help questions make it harder to keep track. Thanks!
