### ISSUE TITLE
Add native EteSync support

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [elementary/calendar#512]
**EteSync** "Secure, end-to-end encrypted, and privacy respecting sync for your contacts, calendars and tasks." Reference to the discussion in the Planner repository alainm23/planner#307 (comment)

I have no experience with EteSync myself, but I find the idea of end-to-end encryption of sensitive data in the context of elementary OS very useful.
This issue should provide room for discussion. Consciously also about possible alternatives, how the desired qualities can be provided independently of certain products.

**Comment by 4jNsY6fCVqZv** [comment]
I have no experience with EteSync myself, but I find the idea of end-to-end encryption of sensitive data in the context of elementary OS very useful.
This issue should provide room for discussion. Consciously also about possible alternatives, how the desired qualities can be provided independently of certain products.

**Comment by danrabbit** [comment]
Closing as "Out of Scope" because Calendar uses Evolution Data Server to abstract backends. An EteSync backend would need to be written for EDS.

**Comment by danrabbit** [comment]
it looks like there's a Summer of Code proposal to add EteSync in EDS already: https://wiki.gnome.org/Outreach/SummerOfCode/2020/Ideas

**Comment by 4jNsY6fCVqZv** [comment]
Sorry, I also just copy and paste ;)

That was my information on which I based this issue.
Should currently already work without the module. Although not as elegant as with an official EDS integration. See this comment: https://github.com/alainm23/planner/issues/307#issuecomment-616221713

So how do you feel about my idea?

**Comment by danrabbit** [comment]
There's nothing to do in Calendar for this. Just need to wait for the EDS module or configure the EteSync server manually on your computer

**Comment by tasn** [comment]
@danrabbit, EteSync is now in EDS! \o/ Should this be reopened? I guess it's related to https://github.com/elementary/switchboard-plug-onlineaccounts/issues/133? (I made the same comment in another ticket)
