### ISSUE TITLE
Visual handling after removing the last calendar

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [elementary/calendar#539]
![screenshot](https://user-images.githubusercontent.com/46536067/84823215-86bfc680-b00d-11ea-94b4-66ec57ea6e7e.png)
Currently, it somehow doesn't look so smooth. I have two thoughts on this. Either it should not be possible to remove the last calendar, or it should only be possible to deactivate it. Or an inviting placeholder text could appear that I can create a new calendar here. Like in the sidebar, for example, when I have not selected a date with an event.

I use an unmodified stable Hera version including all updates.

**Comment by mcclurgm** [comment]
Good catch. I don't know how you even pulled this off, since I can't delete the default Evolution calendars! 🧐️ 

In my view, a label makes sense here. Making it impossible to remove whatever the last calendar is seems kind of odd imo.
It needs some design work to figure out what to put there (if this is the direction we go in), but I gave it a shot. Here's what I came up with: add
```vala
        var no_calendars_label = new Gtk.Label ("Add a calendar to get started.");
        no_calendars_label.wrap = true;
        no_calendars_label.wrap_mode = Pango.WrapMode.WORD;
        no_calendars_label.margin_start = 8;
        no_calendars_label.margin_end = 8;
        no_calendars_label.margin_top = 6;
        no_calendars_label.margin_bottom = 6;
        no_calendars_label.justify = Gtk.Justification.CENTER;
        no_calendars_label.get_style_context ().add_class (Gtk.STYLE_CLASS_DIM_LABEL);
        no_calendars_label.width_chars = 7;
        var placeholder_grid = new Gtk.Grid ();
        placeholder_grid.add (no_calendars_label);
        placeholder_grid.show_all ();

        calendar_box = new Gtk.ListBox ();
        calendar_box.selection_mode = Gtk.SelectionMode.NONE;
        calendar_box.set_header_func (header_update_func);
        calendar_box.set_sort_func ((child1, child2) => {
            var comparison = ((SourceItem)child1).location.collate (((SourceItem)child2).location);
            if (comparison == 0)
                return ((SourceItem)child1).label.collate (((SourceItem)child2).label);
            else
                return comparison;
        });
        calendar_box.set_placeholder (placeholder_grid);
```
This produces the following output:
![Screenshot from 2020-06-17 21 52 08](https://user-images.githubusercontent.com/29022469/84976344-dde49a80-b0e4-11ea-803f-191f820c6001.png)

I added the grid to try to force the ScrolledWindow to show the whole label, but it's still getting truncated as soon as the label wraps to a second line! I'm having a really tough time figuring out how to get this whole label to show without being truncated by the scroll view, even though it's much smaller than the max size. If anyone has suggestions, I'd appreciate it!
![Screenshot from 2020-06-17 21 58 38](https://user-images.githubusercontent.com/29022469/84976674-bf32d380-b0e5-11ea-83e9-852048556368.png)

**Comment by 4jNsY6fCVqZv** [comment]
@mcclurgm Thanks for working on it! About the design: Do any other elementary apps or the HIG give us a hint what a good design for this case could look like?

**Comment by jeremypw** [comment]
When you remove the last calendar, what is giving rise to the events shown in the calendar grid in the images above?

**Comment by mcclurgm** [comment]
Sorry, I should have said this. I just cheated. I couldn't figure out how to delete the last calendars, so I dove into the code and stopped the popover from populating the calendars. So all my calendars are there, just not in the popover.

**Comment by jeremypw** [comment]
@4jNsY6fCVqZv  How did you remove all the calendars on your system? I could only delete those I added myself - not the built-in ones.

**Comment by 4jNsY6fCVqZv** [comment]
@4jNsY6fCVqZv Good question! I don't remember doing any tricks. However, I have not used the application for a while. Are the built-in calendars set up by Calendar itself or by Evolution, which is also available on my system?

**Comment by jeremypw** [comment]
Well, they were there on a clean install.  I think they are provided by `evolution-data-server` which is installed by default.  However, I do not have the Evolution app or other evolution-data-server clients installed (other than io.elementary.calendar and the wingpanel widget) that allows deleting these calendar sources - did you?

**Comment by 4jNsY6fCVqZv** [comment]
I was able to reconstruct it. At some point I had disabled the default calendars "Personal" and "Birthdays and Anniversaries" in the Evolution Account settings.
That is why the field in Calendar is empty when I do not create a new one. And then I get this view.

**Comment by 4jNsY6fCVqZv** [comment]
I guess I also saw a workaround in doing so, because it doesn't seem to be possible within Calendar's user interface to disable these default calendars (or any calendar at all) somehow.

**Comment by 4jNsY6fCVqZv** [comment]
I think I just used this as a workaround, because the user interface of Calendar does not give me the possibility to a) remove these standard calendars or b) at least disable them (e.g. grayed out by flipping a switch).
Of course it is still possible to show or hide the contents of the respective standard calendars using the checkboxes. But since these are empty, this doesn't really help me if I want to remove them completely.

**Comment by jeremypw** [comment]
@4jNsY6fCVqZv 
>  does not give me the possibility to ... at least disable [the standard calendars].

> Of course it is still possible to show or hide the contents of the respective standard calendars using the checkboxes

These statements seem contradictory? You probably need to raise a separate issue if you want Calendar to be able to remove the default evolution-data-server calendars entirely.  You can already disable them with the check boxes.

**Comment by jeremypw** [comment]
@4jNsY6fCVqZv Incidentally, after you removed all calendar sources, what did the calendar grid view look like?  What happened if you tried to add an event?

**Comment by 4jNsY6fCVqZv** [comment]
>  What happened if you tried to add an event?

If there are no more calendars, the "Create a new event" button is still sensitive.
An event dialog window opens, I can make entries in all tabs as usual, but the "Create Event" button remains insensitive. If I focus the title field and press Enter twice in a row, the event dialog window closes again.

I would expect that if there are no calendars, I would not be able to start creating an event at all.

**Comment by 4jNsY6fCVqZv** [comment]
> These statements seem contradictory? [...] You can already disable them with the check boxes.

Yes, sorry, I rather thought that a switch or greying out the calendar name might be visually more appropriate than the check buttons. But of course, you can deactivate them already. I was not very clear in my language.

> You probably need to raise a separate issue if you want Calendar to be able to remove the default evolution-data-server calendars entirely.

How do you feel about that?

**Comment by jeremypw** [comment]
It is not something I would personally make use of, but there may be a use case for other people, I suppose.  You would probably need to add an ability to restore deleted evolution calendars as well. It does no harm to raise the issue for discussion anyway even if there is no guarantee that it will be implemented.

**Comment by 4jNsY6fCVqZv** [comment]
And what are your ideas regarding this issue here?

**Comment by jeremypw** [comment]
Simple "Add a calendar" would be sufficient for me.  This would change to "Add another calendar" when there is already a calendar source.  I do not like "Add a new calendar" because in some cases (CalDav, Google) the calendar already exists.  I would just hide the blank area when there are no calendars.  I am not sure whether a calendar grid is shown at all when there are no calendar sources.  The "Add Event" button should be insensitive.  I suppose the blank area could contain extra information such as "At least one calendar must be added in order to ... add events" i.e. specify what cannot be done without a calendar.

**Comment by 4jNsY6fCVqZv** [comment]
> Simple "Add a calendar" would be sufficient for me. This would change to "Add another calendar" when there is already a calendar source. I do not like "Add a new calendar" because in some cases (CalDav, Google) the calendar already exists.

Sounds reasonable to me. Do you want to create a separate issue for it?

> I would just hide the blank area when there are no calendars.

Sounds good. I would change the Issue title here to reflect your idea. How do you feel about that?

> The "Add Event" button should be insensitive.

Thanks for the new issue!

> I am not sure whether a calendar grid is shown at all when there are no calendar sources.

The grid view is also visible without active calendars.
![Screenshot](https://user-images.githubusercontent.com/46536067/85233728-14c5f380-b3f8-11ea-890d-808819d18080.png)

**Comment by 4jNsY6fCVqZv** [comment]
I have tested it with Odin. With version 6.0.3 Calendar shows that the last calendar is not removable. So I close this issue with gratitude as well!
