### ISSUE TITLE
Label size should be consistent

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [elementary/calendar#541]
![Screenshot](https://user-images.githubusercontent.com/46536067/84826191-1f584580-b012-11ea-955c-0ac3a4d332ef.png)
![Screenshot](https://user-images.githubusercontent.com/46536067/84826240-2e3ef800-b012-11ea-81d7-98d30ff5b89f.png)

**Comment by mcclurgm** [comment]
What is the official placeholder style? We currently have one of them with the style `Granite.STYLE_CLASS_H2_LABEL`, while both of them have `Gtk.STYLE_CLASS_DIM_LABEL`. Are these sorts of big placeholders supposed to be large like H2 or should they be small like the others? Seems to me like most placeholders are small, like in the sidebar, and the header size should be reserved for actual headers.

**Comment by 4jNsY6fCVqZv** [comment]
@mcclurgm Thanks for your comment and @ryonakano thanks for your confirmation! Yes, I was also wondering if there is a consistent style for it. I could not find anything about it in the documents so far. I would like to work on an improvement here!

**Comment by mcclurgm** [comment]
I haven't found anything explicit, but GNOME tends toward standard size in almost all cases. I think that it makes sense to make it standard size (not H2), especially since every other placeholder I've seen in the app uses that style.

**Comment by mcclurgm** [comment]
Finally getting around to closing this.

**Comment by 4jNsY6fCVqZv** [comment]
@mcclurgm Would you like to share a screenshot showing the difference?

**Comment by 4jNsY6fCVqZv** [comment]
@mcclurgm Thanks for the energy you put in! Would you like to share a screenshot showing the difference?

**Comment by mcclurgm** [comment]
Sure, why not? :smiley: Here are the new ones, using the smaller style with consistent coloring:
![Screenshot from 2020-09-03 17 42 18](https://user-images.githubusercontent.com/29022469/92183924-fa9f8d00-ee0c-11ea-9108-68eb06ace5eb.png)
![Screenshot from 2020-09-03 17 42 26](https://user-images.githubusercontent.com/29022469/92183925-fb382380-ee0c-11ea-9329-e1af51d23b95.png)

**Comment by 4jNsY6fCVqZv** [comment]
Wonderful, looks good. Thanks!
