### ISSUE TITLE
Checking or unchecking one calendar as default should not automatically assign the same status to all other calendars

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [elementary/calendar#550]
![Screen record](https://user-images.githubusercontent.com/46536067/85530118-35ab6600-b5fd-11ea-9713-f4bfc6e74e35.gif)

"Birthdays & Anniversaries" and "Personal" are the standard calendars of Evolution in this example.
I use the latest stable and unmodified Hera version including all updates.

**Comment by mcclurgm** [comment]
Thanks for the gif, I'm seeing that too on my git compiled version.

**Comment by 4jNsY6fCVqZv** [comment]
Do you have an idea what causes the problem and how a solution could look like?

**Comment by mcclurgm** [comment]
No, not yet. I haven't looked into what's going on, I just did a quick look to confirm the issue.
