### ISSUE TITLE
Confirm delete event action or provide undo or add undo

### ISSUE THREAD

**Issue by mcclurgm** [elementary/calendar#551]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**
Since Calendar doesn't provide an undo feature, destructive actions like deleting events are easy to do, and don't provide any way to undo or confirm that this is what I wanted. An example of why this matters: today, I wanted to delete a single occurrence of a frequent event. I right-clicked on the event cell and quickly clicked "Remove event" instead of "Remove occurrence". This is easy to do since they're right next to each other. The result was I lost all of my past and future occurrences of that event, with no way to recover them. In general, we should provide either a confirmation or way to walk back destructive actions like this.

**Describe the solution you'd like**

Ideally, to follow the Elementary HIG, we should provide an option to undo these actions.
If that's not possible or we want something else in the meantime, then we should add a confirmation dialog, like you see in Files, for example.

**Existing work**

Here's an example of what a confirmation dialog could look like, from the iOS calendar app Fantasical:
![fantastical](https://user-images.githubusercontent.com/29022469/85602987-26ccaf80-b60d-11ea-8779-44b69a6283dd.PNG)

**Comment by 4jNsY6fCVqZv** [comment]
https://elementary.io/docs/human-interface-guidelines#always-provide-an-undo

**Comment by 4jNsY6fCVqZv** [comment]
For reference see https://elementary.io/docs/human-interface-guidelines#always-provide-an-undo

**Comment by HansCronau** [comment]
Oof that's rough, @mcclurgm. Same thing happened to me: I gave Calendar a spin with Odin's new support for Online Accounts. Now all occurrences of one of my recurring events are gone. No idea how to restore them as they were. That's a pretty good scare. Out of an abundance of caution I decided to uninstall Calendar for now, to prevent myself from making that same mistake again.

**Comment by 4jNsY6fCVqZv** [comment]
@mcclurgm The title of this issue says "Confirm delete event action or provide undo or add undo" -> Does it make sense that Calendar can do both?

**Comment by 4jNsY6fCVqZv** [comment]
@mcclurgm The title of this issue says "Confirm delete event action or provide undo or add undo" -> 
When I take a closer look at the above linked Human Interface Guidelines

> Deleting an item. Instead of asking the user if they are sure, make the item "disappear" from the app, but provide an easy and intuitive way to undo the delete.

I wonder how you decided to use the delete confirmation dialog instead of providing the "undo" option.

**Comment by mcclurgm** [comment]
Simply, it's easier. I want to get a fix out reasonably quick so people stop losing data. If someone else wants to go add undo that would be great, but undo systems are something I'm unfamiliar with and uncomfortable writing myself.

Also, at some point it may make sense to have a dialog anyway. There are some more complex deletion behaviors that many calendar apps implement that may be good for us to include, like deleting only future events or providing an option to delete a single instance or the entire sequence when deleting a recurring event.

**Comment by HansCronau** [comment]
@mcclurgm, great explanation. Also: a dialog allowing me to choose what exactly to delete (this event, this and future events, or all events) was exactly what I expected when I pressed Delete.

**Comment by mcclurgm** [comment]
I agree with that, @HansCronau. I've been trained from other calendar apps that a dialog will appear asking what to delete. My plan is that once I get this simple dialog implemented, I'll open an issue to work with the design team on how/whether to implement that type of dialog and adding an undo system. That's one more thing I didn't mention in my comment is that there will be significant design required to implement an undo system in a way that makes sense for all users, especially if we implement deleting only future events.

All that said, I agree that based on the HIG an undo is always preferable, and should be implemented even if we continue to display dialogs. I intend to work on that when I have the time.
