### ISSUE TITLE
Change colour in dark mode.

### ISSUE THREAD

**Issue by sysadmin-info** [elementary/calendar#552]
https://elementaryos.stackexchange.com/questions/24515/unreadable-calendar-events-in-dark-mode/24984#24984

solution 

Change in /calendar-master/data/style/AgendaEventRow.css
.event {
    background: alpha(@accent_color, 0.15);
    border-radius: 3px;
    color: shade(@accent_color, 0.65);
    padding: 6px;
}

to

.event {
    background: alpha(@accent_color, 0.75);
    border-radius: 3px;
    color: shade(@accent_color, 0.35);
    padding: 6px;
}

**Comment by funder7** [comment]
Hello, there's any chance to have this fix integrated into the app?

**Comment by danrabbit** [comment]
Closing as a duplicate of #267
