### ISSUE TITLE
Comparisons between all-day and not-all-day events fail because of timezones

### ISSUE THREAD

**Issue by mcclurgm** [elementary/calendar#577]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
Not a great title but...
Some event comparisons are failing when we compare their times. This happens when one of them is all-day, and the other is not. This is caused by our treatment of all-day events that i added in #515: they're all in UTC.

### To Reproduce
Here's an example comparison that I just ran into. You can recreate these events with the appropriate differences for your timezone.

I have one event on Sunday at 6:00:32 PM. I have another all-day event on Monday. My local timezone is MDT, UTC-6. With our handling of these timezones, this becomes:
> Event 1: Sunday; start 2020-08-09T18:00:39-0600
> Event 2: Monday; start 2020-08-10T00:00:00+0000
Converted to local time, which is what the comparsion is based on:
> Event 1: Sunday; start 2020-08-09T18:00:39-0600
> Event 2: Monday; start 2020-08-10T18:00:00-0600
Note that event 2's start time is before event 1, even though semantically it clearly comes after, since the event is on Monday.

### Expected behavior

In my example, the later all-day event will be considered later by our code.

## Platform Information

![about](https://user-images.githubusercontent.com/29022469/89687555-0e1b0f00-d8c6-11ea-8daa-384a475a8ecb.png)
- [x] I'm using the latest version from git that I've manually compiled
- [ ] I'm using the latest released stable version

## Additional context

This is down to how to properly treat the timezone of all-day events. I designed this originally following GNOME Calendar, which appears to treat all-day events as UTC. However, given the rest of our implementation, that appears to be the wrong decision. They must have some other code to account for this error.
It's possible that the proper way to deal with this is to treat all-day events in local time. I'll look into this. Any insight would be appreciated, though.

**Comment by marbetschar** [comment]
@mcclurgm don't fully understand where/why you need to compare the time of an all day event at all but:

if we already know it's an all day event, how comes the timezone of that particular object matters?

Can't we just use the timezone of the comparing object?

**Comment by mcclurgm** [comment]
I think that's probably right to treat it with the comparing object. In our case, that means local, since all these times are found by the `get_local_times` function. (Probably, I should just return local times for all-day events from that function) This may be a matter of dealing better with floating timezones, since that's something we have no support for right now. I want to do some research here to be sure, but I agree, I expect that's the answer. Timezones are complicated...

Here's an example of where we do this. This is what my agenda view looks like:
![Screenshot from 2020-08-08 08 50 33](https://user-images.githubusercontent.com/29022469/89713352-d612db00-d95c-11ea-9455-da04c58a4062.png)
Notice the first Monday appears before the Sunday. The AgendaView sort function compares `GLib.DateTimes`, which by necessity includes the time component.

**Comment by mcclurgm** [comment]
Looking at it more, yep, all-day events are supposed to be floating. Our current code doesn't handle floating timezones at all, instead making them UTC. I'll submit a patch to fix that and it should take care of this.
