### ISSUE TITLE
Daily builds are failing

### ISSUE THREAD

**Issue by danrabbit** [elementary/calendar#589]
https://code.launchpad.net/~elementary-os/+recipe/calendar-daily

Looks like its an issue with a failing test

**Comment by mcclurgm** [comment]
Hmm, you're right. I wrote this test, so it should be on me.. Copying the relevant fail line for my future self:
```
# Start of Locale tests
Bail out! ERROR:core/Tests/fd1f8c1@@io.elementary.calendar-tests-model@exe/model-tests.c:209:test_posix_nl_langinfo: assertion failed: (setstr != null)
--- stderr ---
**
ERROR:core/Tests/fd1f8c1@@io.elementary.calendar-tests-model@exe/model-tests.c:209:test_posix_nl_langinfo: assertion failed: (setstr != null)
-------
```

It looks like GLib is failing to set the locale. I'm not sure how this can happen, but according to the docs, a null string indicates a failure.

Just a guess—perhaps the locale I'm setting (`en_GB.utf8`) doesn't exist? Could someone running daily check what locale strings are available? I use `locale -a` on my (18.04) system.
