### ISSUE TITLE
Bad Color Contrast

### ISSUE THREAD

**Issue by Suzie97** [elementary/calendar#612]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature
The color contrast is not good. It is hard to identify the events with different colors. Most of them look similar.

![Screenshot from 2020-10-09 12-28-31](https://user-images.githubusercontent.com/68198116/95552929-3260ac80-0a2b-11eb-977e-d045953b7bb4.png)

Maybe the colors used could be changed to provide a better visual variation.  

The colors used in Google Calendar and Apple Calendar are nice. They are easy to distinguish at a glance.

![Screenshot from 2020-10-09 12-35-15](https://user-images.githubusercontent.com/68198116/95553337-fda12500-0a2b-11eb-8189-3097ab14e2f1.png)

![Screenshot from 2020-10-09 12-34-32](https://user-images.githubusercontent.com/68198116/95553515-5a044480-0a2c-11eb-8ad8-53229f7a5da3.png)

**Comment by cassidyjames** [comment]
To clarify, you're saying the contrast between different colors? The colors are actually extremely similar to the macOS ones you've shown here, you just happen to be using two similar colors for the calendar. I'm not sure how we could make them more different without going for the much brighter label style like Google Calendar, which I like a lot less aesthetically.

Adjacent colors can end up being similar, e.g. Red and Orange, or Orange and Yellow. Not sure if/how we should solve that.

![Screenshot from 2020-10-09 12 27 40](https://user-images.githubusercontent.com/611168/95618830-eca3e400-0a2a-11eb-814b-61f7a7938149.png)

**Comment by danrabbit** [comment]
If we switch these to use selection colors as defined in https://github.com/elementary/stylesheet/pull/852 , these are significantly darker:

![Screenshot from 2020-10-09 14 28 59@2x](https://user-images.githubusercontent.com/7277719/95633403-73ad8800-0a3c-11eb-93ba-1112bf650d2b.png)

Still needs to be checked for contrast, but it would account for dark style and be centralized anyways

**Comment by Suzie97** [comment]
Thanks for such a quick response. I get your point.

I should use different colors.
