### ISSUE TITLE
Create new event button and Go to today's date button not working

### ISSUE THREAD

**Issue by CodeVault** [elementary/calendar#640]
Create new event button and Go to today's date button not working

# Steps to reproduce
1. (issue#1) Open calendar application try adding a new event by clicking 'Create a new event' button (Ctrl + N) on upper left side.
2. (issue#2) Go to other than a current month and try clicking 'Go to today's date ' button( Ctrl + T).

**Comment by cassidyjames** [comment]
@CodeVault please do not ping random people directly in an issue; it just adds noise and annoys people who might not even be related to the codebase.

**Comment by CodeVault** [comment]
Hey @cassidyjames sorry for not following guidelines.I have just started to report bugs from yesterday and I had no idea of guidelines. I'll follow them. Btw Odin looks gorgeous you guys are doing great. 👍👍

**Comment by danrabbit** [comment]
For clicking the new event button we're getting:
```
** (io.elementary.calendar:14330): CRITICAL **: 15:09:00.271: maya_view_calendar_view_get_selected_date: assertion 'self != NULL' failed

** (io.elementary.calendar:14330): CRITICAL **: 15:09:00.271: maya_main_window_on_tb_add_clicked: assertion 'dt != NULL' failed
```

and the today button:
```
maya_view_calendar_view_today: assertion 'self != NULL' failed
```

It looks like this starts happening after 6a44e485956ccee769a00057e8effd22806a1f1a
