### ISSUE TITLE
Can't synchronise Nextcloud calendar

### ISSUE THREAD

**Issue by Suzie97** [elementary/calendar#643]
## What Happened
I copied the private link of my Nextcloud Calendar and tried adding it to Elementary Calendar. I fill in the details required, a dialog appears asking for my password. 

But when I fill in my password, an error is displayed. 

It says something like 401: unauthorized.

**Comment by jeremypw** [comment]
https://github.com/elementary/switchboard-plug-onlineaccounts/pull/121 may be relevant?

**Comment by Suzie97** [comment]
> 
> 
> [elementary/switchboard-plug-onlineaccounts#121](https://github.com/elementary/switchboard-plug-onlineaccounts/pull/121) may be relevant?

The calendar app has an option for CalDav sync. But when I try to sync my Nextcloud calendar, that error is displayed.

I'm not sure if my issue is the same as the one you have mentioned. As per my understanding, I think the issue you have linked is about integrating system wide Nextcloud support. I might be wrong though.

**Comment by fs3o5** [comment]
Do you use 2fa for Nextcloud? If you do, you'll have to create an application specific password.

**Comment by jmbmkn** [comment]
I also have this problem, but nothing as helpful as an error, events just don't appear either way.

**Comment by Suzie97** [comment]
> Do you use 2fa for Nextcloud? If you do, you'll have to create an application specific password.

I don't use 2FA

**Comment by fs3o5** [comment]
Can you make sure you are using the right url to access your calendar? the URL should look like this: 
`https://<yoururl.com>/remote.php/dav/calendars/<username>/<calendarname>/`

If that doesn't work you can also try to setup your calendars using evolution. You can install evolution in the appcenter

**Comment by Suzie97** [comment]
> Can you make sure you are using the right url to access your calendar? the URL should look like this:
> `https://<yoururl.com>/remote.php/dav/calendars/<username>/<calendarname>/`
> 
> If that doesn't work you can also try to setup your calendars using evolution. You can install evolution in the appcenter

My calendar link is similar to the one you have mentioned. 

What do I input in the user and email option? 

My NextCloud username and email or anything

**Comment by Suzie97** [comment]
> > Can you make sure you are using the right url to access your calendar? the URL should look like this:
> > `https://<yoururl.com>/remote.php/dav/calendars/<username>/<calendarname>/`
> > If that doesn't work you can also try to setup your calendars using evolution. You can install evolution in the appcenter
> 
> My calendar link is similar to the one you have mentioned.
> 
> What do I input in the user and email option?
> 
> My NextCloud username and email or anything

What about the password?

Is it the one that I use to log in to Nextcloud, or should I contact my host provider ?

**Comment by jmbmkn** [comment]
> Can you make sure you are using the right url to access your calendar? the URL should look like this:
> `https://<yoururl.com>/remote.php/dav/calendars/<username>/<calendarname>/`
> 
> If that doesn't work you can also try to setup your calendars using evolution. You can install evolution in the appcenter

This fixed it for me, I was trying to use the 'primary CalDAV Address' rather than the 'private link' from Nextcloud

**Comment by fs3o5** [comment]
> What do I input in the user and email option?

Your Nextcloud username. The email shouldn't matter afaik.

>What about the password?
>
>Is it the one that I use to log in to Nextcloud, or should I contact my host provider ?


Yes, you have to use your Nextcloud password.

**Comment by Suzie97** [comment]
I left the email field empty, now it works
