### ISSUE TITLE
Freezes on adding Google Calendar

### ISSUE THREAD

**Issue by kdwk** [elementary/calendar#664]
## What Happened

Calendar freezes for about 1 minute after I add Google Calendar. It has quite a lot of events, but it shouldn't freeze nonetheless. 

## Expected Behavior

Calendar does not freeze and loads the calendar

## Steps to Reproduce

1. Add Google Calendar with a lot of events

## Platform Information

![Screenshot from 2021-05-01 07-12-40](https://user-images.githubusercontent.com/39268094/116774683-ca68c680-aa4d-11eb-96ac-105bff23a73a.png)

**Comment by mcclurgm** [comment]
Thanks for reporting this! It sounds like this is a performance issue with populating many events. We're aware of this issue, and we already have a report in #628 (same issue I believe, just appearing on a different action) so I'm going to close this as a duplicate.
