### ISSUE TITLE
Incorrect accent color in light and dark mode

### ISSUE THREAD

**Issue by greenmanspirit** [elementary/calendar#668]
## What Happened
When I click on a day or an event in the sidebar, the day number circle and event background are lime when my accent color is grape. I tried different accent colors, both light and dark modes and logging out and back in. In all cases, the color is lime.

## Expected Behavior
The color of the day number circle and event background to be grape.

## Steps to Reproduce

1. Set accent color to grape
2. Open Calendar
3. Select days and events

### Logs

No logs

## Platform Information

elementary OS 6.0 Beta fully patched from repo.

**Comment by tintou** [comment]
I think that this is the intended behavior as the application itself is using the lime color accent. Asking @elementary/ux to confirm the intent.

**Comment by cassidyjames** [comment]
Yeah, as noted in System Settings, 

>Used across the system by default. **Apps can always use their own accent color.**

That's what's happening here.
