### ISSUE TITLE
Event alerts are not working

### ISSUE THREAD

**Issue by andirsun** [elementary/calendar#676]
## What Happened

I set 3 alerts for a testing event and none of them trigger an notification or sound.

**EDIT: Only the alert "At time of the event show"**

## Expected Behavior

Send a notification with the event info

## Steps to Reproduce

1. Create event
2. Set alerts 
3. Alerts dont work

### Logs

![Screenshot from 2021-06-30 08-27-39](https://user-images.githubusercontent.com/22928302/123968964-5ed3a480-d97d-11eb-88d2-960ec917e13b.png)

**Comment by shawn1thompson** [comment]
I am having the same issue. When would I expect to see it fixed seeing as it's closed? Thank you.
