### ISSUE TITLE
calendar colors are not working

### ISSUE THREAD

**Issue by freder** [elementary/calendar#686]
## What Happened
the calendar colors are not working as they're supposed to. (I'm using gnome.)

## Expected Behavior
different calendars should have different colors

## Steps to Reproduce
![pantheon-calendar-gnome](https://user-images.githubusercontent.com/724844/128741728-0c784c88-55fc-48f9-8ad4-6bf3c6e21416.png)

### Logs
not sure if related:

```
** (io.elementary.calendar:20740): CRITICAL **: 18:37:35.711: ContractorButtonWithMenu.vala:70: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.elementary.Contractor was not provided by any .service files
```

## Platform Information
* manjaro + gnome 40
* pantheon-calendar version 6.0.0

**Comment by danrabbit** [comment]
Calendar relies on the elementary stylesheet for certain features, like calendar colors. Experiencing breakage like this is normal when using other stylesheets

Closing as "Out of scope", since we can't really force other stylesheets to provide the same features as the elementary stylesheet

**Comment by freder** [comment]
I see. — `GTK_THEME=io.elementary.stylesheet.blueberry:dark io.elementary.calendar` actually works (for me).
thanks for clarifying!
