### ISSUE TITLE
Deprecation Warning: Hdy.Avatar.set_image_load_func

### ISSUE THREAD

**Issue by marbetschar** [elementary/calendar#694]
While compiling the latest master, I noticed the following warning:

```
../src/EventEdition/GuestGrid.vala:111.29-111.54: warning: `Hdy.Avatar.set_image_load_func' has been deprecated since 1.2
```

I had the same warning in elementary Mail and fixed it using [`Hdy.Avatar.set_loadable_icon`](https://github.com/elementary/mail/blob/9477c24201d3c9c3c7bcc650e0290daa0ee1ab21/src/MessageList/MessageListItem.vala#L293). Furthermore I've seen [`Folks`'s avatar seems to be a `LoadableIcon`](https://valadoc.org/folks/Folks.AvatarDetails.avatar.html) - so it might be possible to simply do the following to fix the warning?

```vala
avatar.set_loadable_icon (individual.avatar);
```

**Comment by danrabbit** [comment]
Looks like this was fixed in #716
