### ISSUE TITLE
Created events have wrong timezone

### ISSUE THREAD

**Issue by janxkoci** [elementary/calendar#731]
### What Happened?

I often create events in my calendar, which is connected to my google account and synces across my devices. Recently, I noticed that events that I create on my desktop show up with wrong time on my other devices. The culprit seems to be incorrect timezone. The events are being created with UTC (or GMT, as it is refered to in my phone's calendar app), which is not my timezone.

This was working properly just few weeks/months ago. I don't recall any recent update to calendar though.

### Steps to Reproduce

1. Setup a google account.
2. Create an event and save it.
3. Check on your phone / web version. The time corersponds to UTC instead of my local timezone.

### Expected Behavior

The time of event should be set with correct timezone.

### OS Version

5.x (Hera)

### Software Version

Latest release (I have run all updates)

### Hardware Info

The system was preinstalled by Slimbook, so there are some extras preinstalled. However the problem appeared only recently.

**Comment by mcclurgm** [comment]
If I understand the issue correctly, I believe it was fixed in #653. That fix is available on the latest version, which is only available on 6.x Odin. If you want to get new features and fixes like this one, you'll need to upgrade to the latest version of elementary.
