### ISSUE TITLE
Please add a function to subscribe a online ICS calender stream

### ISSUE THREAD

**Issue by ovz93br43v7** [elementary/calendar#745]
### Problem

I would like to use a ICS calender streams from a online appointment booking system. 

### Proposal

Extend the add calender function so that a subscription of a online ICS calender stream is possible.

### Prior Art (Optional)

On Android I use this app to add ICS calender streams: https://github.com/bitfireAT/icsx5
In GMail it is possible to add such a online calender stream with add additional calenders.

**Comment by mcclurgm** [comment]
Does the CalDAV option not work for you? To the best of my knowledge that adds online calendars in this format.

**Comment by ovz93br43v7** [comment]
> Does the CalDAV option not work for you? To the best of my knowledge that adds online calendars in this format.

No that does not work. ICS calender streams normally don't need any login data, when I use CalDAV I have to enter any login data, but nevertheless it don't show any bookings.
I assume that CalDAV and ICS are two different standards?

In my android app for ICS calenders I only have to add an URL to the ICS calender e.g. https://www.appointman.net/api2/calendar/stream/pitbqb2cgcmkiwaqi4kaq3/ev4tkswe-v5xc-5vr3-h7uh-sfp7wvfte9id.ics
Then I can see all my bookings at my gym. (URL don't work --> anonymized)

**Comment by tintou** [comment]
For anyone wanting to implement this, this is the `webcal` backend in EDS (available in Evolution as "On the Web") option
