### ISSUE TITLE
Support evolution data server 3.45+ / libsoup-3.0 / geocode-glib-2.0

### ISSUE THREAD

**Issue by bobby285271** [elementary/calendar#756]
Not sure if this is really an issue that should be resolved before/during GNOME 43 cycle or just because of me didn't packaged everything properly yet. Building this with evolution data server 3.45.1 fails for me and I think maybe it is caused by libsoup-2.4 clashes with libsoup-3.0, here is the full log:

https://gist.github.com/bobby285271/1a19d13bab9146d0824de0e2a82aa5ac

P.s.: I also mentioned geocode-glib-2.0 in the title as it is built against libsoup-3.0.

---

Actually I am trying to port this but stuck on this line:

https://github.com/elementary/calendar/blob/2b30b8313591336d65cf59e3f29656f5ebe9be2c/plugins/CalDAV/CalDAVBackend.vala#L76

Is replacing it with `dup_uri` only possible on 3.46 due to [this](https://github.com/GNOME/evolution-data-server/blob/af6c1698af43a96917866d49b5a917b9e11c77ae/src/libedataserver/e-source-webdav.c#L1303)? Was getting:

```
../plugins/CalDAV/CalDAVBackend.vala:77.23-77.36: error: `E.SourceWebdav.dup_uri' is not available in libedataserver-1.2 3.45.1. Use libedataserver-1.2 >= 3.46
   77 |             var uri = webdav.dup_uri ();
      |                       ^~~~~~~~~~~~~~ 
```

**Comment by decathorpe** [comment]
Hum, yes, calendar is also broken with e-d-s 3.45.1 on Fedora. It appears that I forgot to file a bug about this one, I filed tickets for all the others. Weird.

**Comment by decathorpe** [comment]
> Building this with evolution data server 3.45.1 fails for me and I think maybe it is caused by libsoup-2.4 clashes with libsoup-3.0, here is the full log:

I'm seeing similar (or the same) build problems on Fedora. This means that ***something*** is pulling in libsoup 2.4 development headers. Turns out, the culprit is calendar itself:
https://github.com/elementary/calendar/blob/master/meson.build#L31

I think this needs a similar conditional (i.e. if e-d-s >= 3.45.1, depend on libsoup-3, else, depend on libsoup-2) to the ones you submitted for other projects, and it might *just work* (maybe with minor code adaptations for changed APIs, like the Soup.URI removal).

**Comment by bobby285271** [comment]
I managed to launches the app, I think we will at least need: 

- https://github.com/elementary/calendar/compare/master...bobby285271:soup3
- https://gitlab.freedesktop.org/geoclue/geoclue/-/merge_requests/129
- https://gitlab.gnome.org/GNOME/libchamplain/-/merge_requests/13

**Comment by tintou** [comment]
You also need this to land in libchamplain to work with libsoup-3: https://gitlab.gnome.org/GNOME/libchamplain/-/merge_requests/13

**Comment by bobby285271** [comment]
Looks like my previous testing is done in an improper way, it looks like with #758 applied and everything GNOME 43.rc and Eds 3.46 (it's out!) both wingpanel-indicator-datetime and calendar does not show any date numbers :disappointed: 

<img src="https://user-images.githubusercontent.com/20080233/190838919-782843ef-7700-481e-bf7c-738572c4c964.png" width=50%>

**Comment by bobby285271** [comment]
Ah it looks like I resolved https://github.com/elementary/calendar/issues/756#issuecomment-1249990402 with https://github.com/bobby285271/calendar/commit/7f3a4be3d26f0656b40fcd326c11e622533d23d0 so *probably* that is not really related to the e-d-s bump (I still not sure what happened though) :see_no_evil:

**Comment by meisenzahl** [comment]
Should be closed by https://github.com/elementary/calendar/issues/756
