### ISSUE TITLE
Support glib 2.73.1+: Avoid property notification during object construction

### ISSUE THREAD

**Issue by bobby285271** [elementary/calendar#761]
### What Happened?

<img src="https://user-images.githubusercontent.com/20080233/190838919-782843ef-7700-481e-bf7c-738572c4c964.png" width=50%>

In https://github.com/elementary/calendar/issues/756#issuecomment-1249990402, we noticed that the calendar app does not show any date numbers, after making a minimal reproducer in https://github.com/bobby285271/e-calendar-issue and bisecting glib commits (thanks `@jtojnar`!), we noticed that [this glib commit](https://gitlab.gnome.org/GNOME/glib/-/commit/8851112b8de024ff6fb4235a4475ffa6c98973dc) intentionally changes the behavior, which is part of glib 2.73.1+. It will be nice to adjust the code here so the app can still work nicely with glib 2.73.1+.

The affected code is at

https://github.com/elementary/calendar/blob/7e65ae0053696b5dae1453ec3ceac391ed870890/src/Grid/GridDay.vala#L104-L107

The workaround is at https://github.com/elementary/calendar/issues/756#issuecomment-1252400047.

### Steps to Reproduce

1. Build with glib 2.73.1+
2. Launch the app
3. Notice the app does not show any date numbers

**Comment by bobby285271** [comment]
I actually don't know how bad the affect will be for other Pantheon apps, for example in https://github.com/NixOS/nixpkgs/pull/192686#issuecomment-1256840424 we also noticed that iconbrowser is affected.

**Comment by jtojnar** [comment]
[This handler](https://github.com/elementary/calendar/blob/641abec284a39072ac4c3a11fdcaa1ce71ad5fa4/core/Services/Calendar/EventStore.vala#L87) might be suffering from the same issue. Although `compute_ranges()` is [already called](https://github.com/elementary/calendar/blob/641abec284a39072ac4c3a11fdcaa1ce71ad5fa4/core/Services/Calendar/EventStore.vala#L80) in the constructor, the [other two methods](https://github.com/elementary/calendar/blob/641abec284a39072ac4c3a11fdcaa1ce71ad5fa4/core/Services/Calendar/EventStore.vala#L453-L454) are not. But I have not checked if they are necessary and am not sure how to test the EventStore.
