### ISSUE TITLE
libsoup-ERROR

### ISSUE THREAD

**Issue by rainer2208** [elementary/calendar#770]
### What Happened?

Hi guys, i am following your project with great interest and frequently use your DE on Arch. 

Over the last couple months, the calendar has shown some difficulties on Arch, and as of the recent updates i got eager and i thought i give it a go. 

The installation went smooth, but upon execution i received the following error: 

(process:2485): libsoup-ERROR **: 15:37:32.790: libsoup2 symbols detected. Using libsoup2 and libsoup3 in the same process is not supported.
Trace/breakpoint trap (core dumped)

any hints? 

### Steps to Reproduce

1. installed the application with meson
2. reinstalled the app with pacman -S pantheon-calendar 

### Expected Behavior

Calendar does not open and when running io.elementary.calendar, throws error  

### OS Version

Other Linux

### Software Version

Latest release (I have run all updates)

### Hardware Info

Linux 6.1.6-arch1-1
Asus Laptop intel core

**Comment by tintou** [comment]
Make sure that all of your dependencies (and Calendar) are either using `libsoup3` or `libsoup2` you can't mix them.

**Comment by rainer2208** [comment]
hi, thanks for the reply ... isn't this the role of the installer? 

if not, how do i make sure that the calendar is using only one of the libs?

**Comment by tintou** [comment]
It's unfortunately not a thing that the build system can cope with, you have to make sure that all the dependencies are built using the correct flags and thus use libsoup3 or libsoup2 only.

**Comment by Bundy01** [comment]
@tintou 
"Make sure that all of your dependencies (and Calendar) are either using libsoup3 or libsoup2 you can't mix them."

How to do it? Is the problem due to the Archlinux package?

**Comment by alucryd** [comment]
Yes, and there's not much Arch can do at the moment either, most of the calendar's deps use libsoup 2, but the newest evolution-data-server uses libsoup 3. Short of creating a compat eds package which uses libsoup 2, which I really don't want to, this was already voted against during the last GNOME update when calendar didn't support the latest eds. This libsoup business is going to bite more than calendar, I'm really not looking forward to it.

**Comment by tintou** [comment]
@alucryd the only dependency we are using that is still not libsoup3 is libchamplain for which you can use this patch https://gitlab.gnome.org/GNOME/libchamplain/-/merge_requests/13 Is there anything else missing?

**Comment by alucryd** [comment]
Thanks for the link to the patch! On arch we still have geoclue (and geoclue-glib) that use libsoup and are deps of calendar. The best move for us would be to completely remove libsoup 2 from our repos, as long as we have both we're bound to run into similar issues. I'll take it to our GNOME maintainer, maybe libchamplain was a blocker when he pushed the latest GNOME.

**Comment by tintou** [comment]
Yeah geoclue is also [ported to libsoup3](https://gitlab.freedesktop.org/geoclue/geoclue/-/commit/66dbd6decf607ade17bc845c84e8cf5c5ceb8a53) but is not released yet

**Comment by alucryd** [comment]
So we probably won't be updating libchamplain, apparently it's been superseded by libshumate, but it's GTK4. Do you have plans to migrate to it with the move to granite 7?

**Comment by tintou** [comment]
Yes the plan is to upgrade everything but I don't have an ETA for this

**Comment by alucryd** [comment]
No worries, just knowing it's planned is great news, thanks for all the information :)

**Comment by alucryd** [comment]
Oh well, looks like champlain just got released with your patch :) It's in our testing repo, calendar starts again with the new release. As for geoclue, only its daemon requires libsoup so that one is fine as is.

Should land in our extra repo soon.

**Comment by alucryd** [comment]
@rainer2208 no need, pantheon-calendar doesn't need to be rebuilt, you just need libchamplain.

**Comment by rainer2208** [comment]
cool .... that worked, bravo

**Comment by rainer2208** [comment]
hi guys, many thanks for the attention and the time .. they say that Arch is for tinkerer and in my  case this is absolutely true. But i often reach my limits and through the competence and of the (Arch) developers, i always gain the chance to acquire new - humble - skills and interesting insights. 

Beauty is also something that attracts me a lot and when i want to look at something pretty, i always load Pantheon. 

Since the issue seems to be solved and i am going to close this.
