### ISSUE TITLE
Use the background portal

### ISSUE THREAD

**Issue by tintou** [elementary/calendar#778]
We are currently using the .deb package to install the background service, we should install it at first run via the background service portal https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.Background

**Comment by Marukesu** [comment]
There's #681, however we cannot use it outside of the flatpak version because host applications have a empty app-id and that's used to create the autostart file.

**Comment by danirabbit** [comment]
Fixed in #681
